/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AccountIntegration {
    /**
    * Company name.
    */
    'name': string;
    /**
    * Category or categories this integration belongs to.
    */
    'categories'?: Array<AccountIntegration.CategoriesEnum>;
    /**
    * Company logo in rectangular shape.
    */
    'image'?: string | null;
    /**
    * Company logo in square shape.
    */
    'squareImage'?: string | null;
    /**
    * The color of this integration used for buttons and text throughout the app and landing pages.
    */
    'color'?: string;
    'slug'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<AccountIntegration.CategoriesEnum>"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "squareImage",
            "baseName": "square_image",
            "type": "string"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AccountIntegration.attributeTypeMap;
    }
}

export namespace AccountIntegration {
    export enum CategoriesEnum {
        Hris = <any> 'hris',
        Ats = <any> 'ats',
        Accounting = <any> 'accounting'
    }
}
