/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityTypeEnum } from './activityTypeEnum';
import { RemoteData } from './remoteData';
import { VisibilityEnum } from './visibilityEnum';

/**
* # The Activity Object ### Description The `Activity` object is used to represent an activity performed by a user.  ### Usage Example Fetch from the `LIST Activities` endpoint and filter by `ID` to show all activities.
*/
export class Activity {
    'id'?: string;
    /**
    * The third-party API ID of the matching object.
    */
    'remoteId'?: string | null;
    /**
    * The user the performed the action.
    */
    'user'?: string | null;
    /**
    * When the third party\'s activity was created.
    */
    'remoteCreatedAt'?: Date | null;
    /**
    * The activity\'s type.
    */
    'activityType'?: ActivityTypeEnum | null;
    /**
    * The activity\'s subject.
    */
    'subject'?: string | null;
    /**
    * The activity\'s body.
    */
    'body'?: string | null;
    /**
    * The activity\'s visibility.
    */
    'visibility'?: VisibilityEnum | null;
    'remoteData'?: Array<RemoteData> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "remoteId",
            "baseName": "remote_id",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string"
        },
        {
            "name": "remoteCreatedAt",
            "baseName": "remote_created_at",
            "type": "Date"
        },
        {
            "name": "activityType",
            "baseName": "activity_type",
            "type": "ActivityTypeEnum"
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "VisibilityEnum"
        },
        {
            "name": "remoteData",
            "baseName": "remote_data",
            "type": "Array<RemoteData>"
        }    ];

    static getAttributeTypeMap() {
        return Activity.attributeTypeMap;
    }
}

