/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Attachment } from './attachment';
import { ValidationProblem } from './validationProblem';

export class AttachmentResponse {
    'errors': Array<ValidationProblem>;
    'warnings': Array<ValidationProblem>;
    'model': Attachment;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<ValidationProblem>"
        },
        {
            "name": "warnings",
            "baseName": "warnings",
            "type": "Array<ValidationProblem>"
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "Attachment"
        }    ];

    static getAttributeTypeMap() {
        return AttachmentResponse.attributeTypeMap;
    }
}

