/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EmailAddressRequest } from './emailAddressRequest';
import { PhoneNumberRequest } from './phoneNumberRequest';
import { UrlRequest } from './urlRequest';

/**
* # The Candidate Object ### Description The `Candidate` object is used to represent a Candidate for various positions.  ### Usage Example Fetch from the `LIST Candidates` endpoint and filter by `ID` to show all candidates.
*/
export class CandidateRequest {
    /**
    * The third-party API ID of the matching object.
    */
    'remoteId'?: string | null;
    /**
    * The candidate\'s first name.
    */
    'firstName'?: string | null;
    /**
    * The candidate\'s last name.
    */
    'lastName'?: string | null;
    /**
    * The candidate\'s current company.
    */
    'company'?: string | null;
    /**
    * The candidate\'s current title.
    */
    'title'?: string | null;
    /**
    * When the third party\'s candidate was created.
    */
    'remoteCreatedAt'?: Date | null;
    /**
    * When the third party\'s candidate was updated.
    */
    'remoteUpdatedAt'?: Date | null;
    /**
    * When the most recent candidate interaction occurred.
    */
    'lastInteractionAt'?: Date | null;
    /**
    * Whether or not the candidate is private.
    */
    'isPrivate'?: boolean | null;
    /**
    * Whether or not the candidate can be emailed.
    */
    'canEmail'?: boolean | null;
    /**
    * The candidate\'s locations.
    */
    'locations'?: Array<string> | null;
    'phoneNumbers'?: Array<PhoneNumberRequest>;
    'emailAddresses'?: Array<EmailAddressRequest>;
    'urls'?: Array<UrlRequest>;
    /**
    * Array of `Tag` names as strings.
    */
    'tags'?: Array<string>;
    /**
    * Array of `Application` object IDs.
    */
    'applications'?: Array<string>;
    /**
    * Array of `Attachment` object IDs.
    */
    'attachments'?: Array<string>;
    /**
    * Custom fields configured for a given model.
    */
    'customFields'?: { [key: string]: any; } | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "remoteId",
            "baseName": "remote_id",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string"
        },
        {
            "name": "company",
            "baseName": "company",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "remoteCreatedAt",
            "baseName": "remote_created_at",
            "type": "Date"
        },
        {
            "name": "remoteUpdatedAt",
            "baseName": "remote_updated_at",
            "type": "Date"
        },
        {
            "name": "lastInteractionAt",
            "baseName": "last_interaction_at",
            "type": "Date"
        },
        {
            "name": "isPrivate",
            "baseName": "is_private",
            "type": "boolean"
        },
        {
            "name": "canEmail",
            "baseName": "can_email",
            "type": "boolean"
        },
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<string>"
        },
        {
            "name": "phoneNumbers",
            "baseName": "phone_numbers",
            "type": "Array<PhoneNumberRequest>"
        },
        {
            "name": "emailAddresses",
            "baseName": "email_addresses",
            "type": "Array<EmailAddressRequest>"
        },
        {
            "name": "urls",
            "baseName": "urls",
            "type": "Array<UrlRequest>"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "applications",
            "baseName": "applications",
            "type": "Array<string>"
        },
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "Array<string>"
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "{ [key: string]: any; }"
        }    ];

    static getAttributeTypeMap() {
        return CandidateRequest.attributeTypeMap;
    }
}

