/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DisabilityStatusEnum } from './disabilityStatusEnum';
import { GenderEnum } from './genderEnum';
import { RaceEnum } from './raceEnum';
import { RemoteData } from './remoteData';
import { VeteranStatusEnum } from './veteranStatusEnum';

/**
* # The EEOC Object ### Description The `EEOC` object is used to represent the Equal Employment Opportunity Commission information for a candidate.  ### Usage Example Fetch from the `LIST EEOCs` endpoint and filter by `candidate` to show all EEOC information for a candidate.
*/
export class EEOC {
    'id'?: string;
    /**
    * The third-party API ID of the matching object.
    */
    'remoteId'?: string | null;
    /**
    * The candidate being represented.
    */
    'candidate'?: string | null;
    /**
    * When the information was submitted.
    */
    'submittedAt'?: Date | null;
    /**
    * The candidate\'s race.
    */
    'race'?: RaceEnum | null;
    /**
    * The candidate\'s gender.
    */
    'gender'?: GenderEnum | null;
    /**
    * The candidate\'s veteran status.
    */
    'veteranStatus'?: VeteranStatusEnum | null;
    /**
    * The candidate\'s disability status.
    */
    'disabilityStatus'?: DisabilityStatusEnum | null;
    'remoteData'?: Array<RemoteData> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "remoteId",
            "baseName": "remote_id",
            "type": "string"
        },
        {
            "name": "candidate",
            "baseName": "candidate",
            "type": "string"
        },
        {
            "name": "submittedAt",
            "baseName": "submitted_at",
            "type": "Date"
        },
        {
            "name": "race",
            "baseName": "race",
            "type": "RaceEnum"
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "GenderEnum"
        },
        {
            "name": "veteranStatus",
            "baseName": "veteran_status",
            "type": "VeteranStatusEnum"
        },
        {
            "name": "disabilityStatus",
            "baseName": "disability_status",
            "type": "DisabilityStatusEnum"
        },
        {
            "name": "remoteData",
            "baseName": "remote_data",
            "type": "Array<RemoteData>"
        }    ];

    static getAttributeTypeMap() {
        return EEOC.attributeTypeMap;
    }
}

