/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EndUserDetailsRequest {
    'end_user_email_address': string;
    'end_user_organization_name': string;
    'end_user_origin_id': string;
    'categories'?: Array<EndUserDetailsRequest.CategoriesEnum>;
    'integration'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "end_user_email_address",
            "baseName": "end_user_email_address",
            "type": "string"
        },
        {
            "name": "end_user_organization_name",
            "baseName": "end_user_organization_name",
            "type": "string"
        },
        {
            "name": "end_user_origin_id",
            "baseName": "end_user_origin_id",
            "type": "string"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<EndUserDetailsRequest.CategoriesEnum>"
        },
        {
            "name": "integration",
            "baseName": "integration",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EndUserDetailsRequest.attributeTypeMap;
    }
}

export namespace EndUserDetailsRequest {
    export enum CategoriesEnum {
        Hris = <any> 'hris',
        Ats = <any> 'ats',
        Accounting = <any> 'accounting'
    }
}
