/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssueStatusEnum } from './issueStatusEnum';

export class Issue {
    'id'?: string;
    'status'?: IssueStatusEnum;
    'errorDescription': string;
    'endUser'?: { [key: string]: any; };
    'firstIncidentTime'?: Date | null;
    'lastIncidentTime'?: Date | null;
    'isMuted'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "IssueStatusEnum"
        },
        {
            "name": "errorDescription",
            "baseName": "error_description",
            "type": "string"
        },
        {
            "name": "endUser",
            "baseName": "end_user",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "firstIncidentTime",
            "baseName": "first_incident_time",
            "type": "Date"
        },
        {
            "name": "lastIncidentTime",
            "baseName": "last_incident_time",
            "type": "Date"
        },
        {
            "name": "isMuted",
            "baseName": "is_muted",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Issue.attributeTypeMap;
    }
}

