/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* # The ModelOperation Object ### Description The `ModelOperation` object is used to represent the operations that are currently supported for a given model.  ### Usage Example View what operations are supported for the `Candidate` endpoint.
*/
export class ModelOperation {
    'modelName': string;
    'availableOperations': Array<string>;
    'requiredPostParameters': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "modelName",
            "baseName": "model_name",
            "type": "string"
        },
        {
            "name": "availableOperations",
            "baseName": "available_operations",
            "type": "Array<string>"
        },
        {
            "name": "requiredPostParameters",
            "baseName": "required_post_parameters",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ModelOperation.attributeTypeMap;
    }
}

