/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OfferStatusEnum } from './offerStatusEnum';
import { RemoteData } from './remoteData';

/**
* # The Offer Object ### Description The `Offer` object is used to represent an offer for an application.  ### Usage Example Fetch from the `LIST Offers` endpoint and filter by `ID` to show all offers.
*/
export class Offer {
    'id'?: string;
    /**
    * The third-party API ID of the matching object.
    */
    'remoteId'?: string | null;
    /**
    * The application who is receiving the offer.
    */
    'application'?: string | null;
    /**
    * The user who created the offer.
    */
    'creator'?: string | null;
    /**
    * When the third party\'s offer was created.
    */
    'remoteCreatedAt'?: Date | null;
    /**
    * When the offer was closed.
    */
    'closedAt'?: Date | null;
    /**
    * When the offer was sent.
    */
    'sentAt'?: Date | null;
    /**
    * The employment start date on the offer.
    */
    'startDate'?: Date | null;
    /**
    * The offer\'s status.
    */
    'status'?: OfferStatusEnum | null;
    'remoteData'?: Array<RemoteData> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "remoteId",
            "baseName": "remote_id",
            "type": "string"
        },
        {
            "name": "application",
            "baseName": "application",
            "type": "string"
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "string"
        },
        {
            "name": "remoteCreatedAt",
            "baseName": "remote_created_at",
            "type": "Date"
        },
        {
            "name": "closedAt",
            "baseName": "closed_at",
            "type": "Date"
        },
        {
            "name": "sentAt",
            "baseName": "sent_at",
            "type": "Date"
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "Date"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "OfferStatusEnum"
        },
        {
            "name": "remoteData",
            "baseName": "remote_data",
            "type": "Array<RemoteData>"
        }    ];

    static getAttributeTypeMap() {
        return Offer.attributeTypeMap;
    }
}

