/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UpdateApplicationStageRequest {
    /**
    * The interview stage to move the application to.
    */
    'job_interview_stage'?: string | null;
    'remote_user_id'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "job_interview_stage",
            "baseName": "job_interview_stage",
            "type": "string"
        },
        {
            "name": "remote_user_id",
            "baseName": "remote_user_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdateApplicationStageRequest.attributeTypeMap;
    }
}

